### ISSUE TITLE
SEBServer is running into an Error while connecting to the MySQL 

### ISSUE THREAD

**Issue by RAZA-ABBBASI** [SafeExamBrowser/seb-server-setup#10]
**Describe the bug**
HikariPool-1 - Exception during pool initialization.
java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=seb-server-mariadb)(port=3306)(type=master) : (conn=32) Access denied for user 'root'@'172.19.0.3' (using password: YES)

**To Reproduce**
1. Install the prod on the ubuntu machine

**Comment by anhefti** [comment]
Hi, It seems the DB password is not set correctly, either on the DB side or the SEB Server side (or both sides).

What setup do you actually use, prod/basic or prod/dockerhub?
In the dockerhub setup, please make sure you have set the DB_SA_PWD environment variable before startup.
In the basic setup make sure that the "secret" file you have to create on the setup process is correct set.
