### ISSUE TITLE
Wrong username or password with the credentials displayed with docker-compose logs -f

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-server-setup#12]
![image](https://github.com/SafeExamBrowser/seb-server-setup/assets/1741341/e815594d-cc57-4057-a5b3-0c3d8ba048fd)

![image](https://github.com/SafeExamBrowser/seb-server-setup/assets/1741341/962318c9-091a-4a73-badd-7735b1158f12)

I ran and logged in SEB server successfully a week ago. I accidentally deleted the docker-compose.yml folder yesterday. Now:

1. I reconstruct the `docker-compose .yml` file and .`env` file, the latter contains only `DB_SA_PWD `and `SEBSERVER_PWD`.
2. run `docker-compose down -v`
3. run `docker-compose up -d`
4. Try the username & passwords displayed with `docker-compose logs -f` and set in the `.env` file, both failed.

I cannot figure out why.

**Comment by anhefti** [comment]
Hi, 

- the docker-compose.yml is not a folder but a file. What exactly have you deleted?
- It seems that your startup has created a new super-admin user. This should not happen if there is already one in our DB from later initialization. Either you have a entirely new, empty DB or you have set a different password for SEBSERVER_PWD as before. 
- Note that the SEBSERVER_PWD must be the same as before when you access already existing data. 
- If you have forgotten your old SEBSERVER_PWD you need to start from scratch with a new empty DB.
- Please also provide more information (always SEB Server logs)

**Comment by fishfree** [comment]
@anhefti  Sorry to reply late. I even ran `docker-compose down -v && docker image prune -a -y && docker-compose up -d` . Still no luck.
This is the log file. Thank you!
[sebserverdocker.log](https://github.com/SafeExamBrowser/seb-server-setup/files/12066922/sebserverdocker.log)

**Comment by anhefti** [comment]
You have to delete the sebserver-admin account on your databse that was automatically generated by SEB Server on the very first startup with empty database. Once you have deleted this account on your database SEB Server should create a new one for you and prints the password as usual within the logs.

**Comment by fishfree** [comment]
@anhefti I ran:
```
docker exec -it seb-server-mariadb /bin/bash
mysql
use SEBServer;
DELETE FROM user_role;
DELETE FROM user;
exit
exit
docker-compose restart seb-server
```

Now use the newly-generated password to login in, the same error. 

Did you notice this line in my log: 
`[36mseb-server    |[0m 07:19:37.090 INFO  [main]:[ch.ethz.seb.SEB_SERVER_INIT] ----> Webservice connection: https://examserver.example.com:8080/admin-api/v1`

I cannot access this URL publicly.

**Comment by fishfree** [comment]
Thank you for your tip! After manually adding these in the docker-compose.yml file, it works now.
```
sebserver_gui_webservice_protocol=http
sebserver_gui_webservice_address=seb-server
sebserver_gui_webservice_port=8080
```
