### ISSUE TITLE
Switch to Helm rather than using kustomize

### ISSUE THREAD

**Issue by mark-webster-catalyst** [SafeExamBrowser/seb-server-setup#26]
You will quickly run into problems and limitations using kustomize as the basis for the kubernetes deployment, I would strongly suggest switching to Helm.

**Comment by BenGig** [comment]
Personally I am not a fan of Helm, based on 5 years of Kubernetes operations. We use ArgoCD for deployments, and kustomize is far superior in combination with ArgoCD. Especially if you use sealed-secrets and/or an external secrets vault. Running several hundreds of deployments, I have not yet encountered limitations with kustomize, in contrast to Helm.

However, contributions are welcome.
