### ISSUE TITLE
Getting error with url insertion. 

### ISSUE THREAD

**Issue by erainterfacesindia** [SafeExamBrowser/seb-server-setup#4]
Hi, 

I wanted to appreciate the efforts and your contribution to this SEB server & Jitsi integration. 
Can u please let me know where to change the server URL for demo, & production. 

**Do I need to change the URL here or ?**

# Server address (set for docker internal)
server.address=0.0.0.0
# Server http port
server.port=8080
# The servlet context path
server.servlet.context-path=/

**Here ??**

sebserver.webservice.distributed=false
sebserver.webservice.http.external.scheme=http
sebserver.webservice.http.external.servername=ralph.ethz.ch

**Comment by anhefti** [comment]
Hi,

For installation please refer to the [Installation Guide](https://seb-server-setup.readthedocs.io/en/latest/overview.html)
If you have a simple docker setup:

server.address=0.0.0.0 and server.port=8080 are used docker internally and there is no need to change that. In the docker-compose.yml file you can make the port mapping to the host.

Then the following settings: 
sebserver.webservice.http.external.scheme=http
sebserver.webservice.http.external.servername=ralph.ethz.ch
sebserver.webservice.http.external.port=

defines the URL from where your SEB Server instance is externally available. So if your host on that SEB Server is running is accessible through e.g: https://demo.myhost.com, set as following;
sebserver.webservice.http.external.scheme=https
sebserver.webservice.http.external.servername=demo.myhost.com

if you don't want to access SEB Server on the root of the host URL, you have to change the server.servlet.context-path=/ setting.
E.g: https://demo.myhost.com/mysebserver/, set as following;
server.servlet.context-path=/mysebserver
But we don't recommend this as we didn't test this yet.
